version: "3"

services:
  # Reverse Proxy
  nginx-proxy:
    container_name: web-proxy
    image: alexanderkrause/rpi-nginx-proxy:${PROXY_VERSION}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs:ro
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/challenges:/usr/share/nginx/html

  https-companion:
    container_name: web-https
    depends_on:
      - nginx-proxy
    image: alexanderkrause/rpi-letsencrypt-nginx-proxy-companion:${PROXY_VERSION}
    environment:
      - NGINX_PROXY_CONTAINER=web-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/challenges:/usr/share/nginx/html

networks:
  default:
    driver: bridge
